apiVersion: v2
icon: https://helm.sh/img/helm.svg
name: sre-metrics-exporter
version: 1.0.0
description: Prometheus SRE metrics exporter
maintainers:
- name: maksim-paskal  # Maksim Paskal
  email: paskal.maksim@gmail.com
